App\Entity\WalletTransaction:
  constraints:
    - App\Validator\Constraint\WalletTransactionAmountConstraint: ~
  attributes:
    amount:
      - Symfony\Component\Validator\Constraints\Sequentially:
          - NotBlank: ~
          - PositiveOrZero: ~