App\Form\Model\LoginUserModel:
  properties:
    username:
      - NotBlank: ~
    password:
      - Symfony\Component\Validator\Constraints\Sequentially:
          - NotBlank: ~
          - Length:
              min: 6
              max: 4096
              minMessage: 'Your password should be at least {{ limit }} characters'