version: '3.8'

services:
  text-test:
    container_name: text-test
    ports:
      - "80:80"
    build:
      context: .
      args:
        - APP_ENV=dev
    volumes:
      # The "cached" option has no effect on Linux but improves performance on Mac
      - ./:/var/www/txt-mgc-int:cached
    env_file:
      - ./docker/.env.local
    depends_on:
      - text-test-postgres

  text-test-postgres:
    container_name: text-test-postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_PASSWORD: password
      POSTGRES_USER: test
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data

###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
